deploy:
  name: "exampleapi"
  podLabel: "web"
  label: "exampleapi-deploy"
replicaCount: 1

image:
  repository: zhuyunjie0207/demo_web_api
  tag: "test"

service:
  type: ClusterIP
  port: 80
  nodePort: 30009
  label: exampleapi
  name: exampleapi-service
