apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploy.name}}
  labels: 
    app: {{ .Values.deploy.label}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploy.podLabel}}
  template:
    metadata:
      labels:
        app: {{ .Values.deploy.podLabel}}
    spec:
      containers:
        - name: {{ .Values.deploy.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
