apiVersion: v1
kind: Service
metadata:
  name: {{ include "exampleAPI.fullname" . }}
  labels:
    {{- include "exampleAPI.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
      {{- if .Values.service.type == "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end}}
  selector:
    {{- include "exampleAPI.selectorLabels" . | nindent 4 }}
